#ruby=ruby-1.8.7
#ruby-gemset=oauth2-sinatra-test-provider

source :rubygems

gem 'sinatra'
gem 'mongo'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'bson_ext'
gem 'json'

group :development do
end

group :test do
end

group :production do
end
